project:
  type: website

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    smooth-scroll: true
    html-math-method: mathjax

website:
  title: "Electromagnetism"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: electromagnetism.qmd
        text: Notes
